name: Keys Dragon HUB

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  generate-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Tạo key
        run: |
          function generate_random {
            cat /dev/urandom | tr -dc 'A-Za-z0-9' | fold -w 6 | head -n 1
          }

          # Sinh ra các chuỗi 6 ký tự không trùng
          key1=$(generate_random)
          key2=$(generate_random)
          while [[ "$key2" == "$key1" ]]; do
            key2=$(generate_random)
          done
          key3=$(generate_random)
          while [[ "$key3" == "$key1" || "$key3" == "$key2" ]]; do
            key3=$(generate_random)
          done

          generated_key="Dragon-HUB_${key1}-${key2}-${key3}"
          echo "Generated Key: $generated_key"

          echo $generated_key > Key

      - name: Commit và push file Key
        run: |
          git add Key
          git commit -m "Cập nhật key mới: $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
